# Generated by Django 3.1.6 on 2021-02-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210219_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
